[package]
edition.workspace = true
name = "koe-core"
version.workspace = true

[features]
aec = []
cli = []
default = ["aec", "cli", "ogg", "screen-audio", "system-audio"]
gui = []
ogg = []
screen-audio = []
system-audio = []

[dependencies]
fs2 = { workspace = true }
koe-ffi = { path = "../koe-ffi" }
log = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-util", "macros", "rt-multi-thread", "sync", "time"] }

[lints]
workspace = true
