[package]
edition.workspace = true
name = "koe-cli"
version.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
koe-core = { path = "../koe-core" }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
