#![allow(clippy::derive_partial_eq_without_eq)] // Generated by GPUI's `actions!` macro.

use std::{
    fs,
    path::{Path, PathBuf},
    sync::mpsc,
    thread,
    time::Duration,
};

use gpui::{
    App, Application, Bounds, Context, Div, ElementId, FocusHandle, FontWeight, KeyBinding,
    Stateful, Window, WindowBounds, WindowOptions, actions, div, prelude::*, px, rgb, size,
};
use koe_app::{
    RecorderCoordinator, RecordingConsent, SessionSnapshot,
    desktop::{DesktopPage, DesktopSettings, DesktopViewModel, SourceStatus},
};
use koe_audio::{
    AudioBackend, AudioCapability, AudioDevice, AudioStream, CpalBackend, OpenSource, frame_ring,
};
use koe_core::{NetworkPolicy, SourceKind};
use koe_model::{DigestAllowlist, FoundryLocalAdapter, KoeModelManager};
use koe_recording::SessionManifest;
use koe_recording::{RecordingConfig, TrackKind};
use serde::{Deserialize, Serialize};

actions!(koe_desktop, [Tab, TabPrev]);

const BACKGROUND: u32 = 0x0011_1410;
const PANEL: u32 = 0x001c_211b;
const BORDER: u32 = 0x0039_4137;
const TEXT: u32 = 0x00f0_f2e9;
const MUTED: u32 = 0x00a7_afa0;
const ACCENT: u32 = 0x00d5_f36b;
const DANGER: u32 = 0x00ff_766e;

#[derive(Clone, Debug)]
struct SessionRow {
    id: String,
    state: String,
    duration_ms: u64,
    files: usize,
    has_transcript: bool,
}

#[derive(Clone, Debug)]
struct ModelRow {
    id: String,
    alias: String,
    version: String,
    provider: String,
    license: String,
    size: u64,
}

enum WorkerCommand {
    Start {
        data_root: PathBuf,
        device_id: String,
        consent: RecordingConsent,
    },
    Stop,
    Shutdown,
}

enum WorkerEvent {
    Snapshot(SessionSnapshot),
    Error {
        code: &'static str,
        message: &'static str,
    },
}

struct CaptureWorker {
    commands: mpsc::Sender<WorkerCommand>,
    events: mpsc::Receiver<WorkerEvent>,
}

impl CaptureWorker {
    fn spawn() -> Self {
        let (command_tx, command_rx) = mpsc::channel();
        let (event_tx, event_rx) = mpsc::channel();
        let _worker = thread::Builder::new()
            .name("koe-desktop-capture".to_owned())
            .spawn(move || capture_worker(&command_rx, &event_tx));
        Self {
            commands: command_tx,
            events: event_rx,
        }
    }

    fn start(
        &self,
        data_root: PathBuf,
        device_id: String,
        consent: RecordingConsent,
    ) -> Result<(), mpsc::SendError<WorkerCommand>> {
        self.commands.send(WorkerCommand::Start {
            data_root,
            device_id,
            consent,
        })
    }

    fn stop(&self) -> Result<(), mpsc::SendError<WorkerCommand>> {
        self.commands.send(WorkerCommand::Stop)
    }
}

impl Drop for CaptureWorker {
    fn drop(&mut self) {
        let _ignored = self.commands.send(WorkerCommand::Shutdown);
    }
}

#[derive(Clone, Debug, Deserialize, Serialize)]
struct StoredSettings {
    schema_version: u32,
    retention_days: Option<u32>,
    diagnostics_enabled: bool,
    offline_only: bool,
}

impl Default for StoredSettings {
    fn default() -> Self {
        let settings = DesktopSettings::default();
        Self {
            schema_version: 1,
            retention_days: settings.retention_days,
            diagnostics_enabled: settings.diagnostics_enabled,
            offline_only: settings.offline_only,
        }
    }
}

struct KoeDesktop {
    model: DesktopViewModel,
    data_root: PathBuf,
    devices: Vec<AudioDevice>,
    models: Vec<ModelRow>,
    sessions: Vec<SessionRow>,
    capture: CaptureWorker,
    focus: FocusHandle,
}

impl KoeDesktop {
    fn new(
        window: &mut Window,
        cx: &Context<Self>,
    ) -> Self {
        let data_root = data_root();
        let _created = fs::create_dir_all(&data_root);
        let (sources, devices) = load_audio();
        let models = load_models(&data_root);
        let sessions = load_sessions(&data_root);
        let settings = load_settings(&data_root);
        let mut model = DesktopViewModel::default();
        model.replace_sources(sources);
        model.set_settings(DesktopSettings {
            retention_days: settings.retention_days,
            diagnostics_enabled: settings.diagnostics_enabled,
            offline_only: settings.offline_only,
        });
        if let Some(device) = devices
            .iter()
            .find(|device| device.kind == SourceKind::Microphone)
        {
            model.select_microphone(device.id.clone());
        }
        if let Some(installed) = models.first() {
            model.select_model(Some(installed.id.clone()));
        }
        let focus = cx.focus_handle();
        window.focus(&focus);
        let desktop = Self {
            model,
            data_root,
            devices,
            models,
            sessions,
            capture: CaptureWorker::spawn(),
            focus,
        };
        cx.spawn(async move |entity, cx| {
            loop {
                cx.background_executor()
                    .timer(Duration::from_millis(100))
                    .await;
                if entity
                    .update(cx, |desktop, cx| {
                        desktop.poll_capture_events();
                        cx.notify();
                    })
                    .is_err()
                {
                    break;
                }
            }
        })
        .detach();
        desktop
    }

    fn navigate(
        &mut self,
        page: DesktopPage,
        cx: &mut Context<Self>,
    ) {
        self.model.navigate(page);
        if page == DesktopPage::Sessions {
            self.sessions = load_sessions(&self.data_root);
        } else if page == DesktopPage::Models {
            self.models = load_models(&self.data_root);
        }
        cx.notify();
    }

    #[allow(clippy::unused_self)]
    fn on_tab(
        &mut self,
        _: &Tab,
        window: &mut Window,
        _: &mut Context<Self>,
    ) {
        window.focus_next();
    }

    #[allow(clippy::unused_self)]
    fn on_tab_prev(
        &mut self,
        _: &TabPrev,
        window: &mut Window,
        _: &mut Context<Self>,
    ) {
        window.focus_prev();
    }

    fn poll_capture_events(&mut self) {
        while let Ok(event) = self.capture.events.try_recv() {
            match event {
                WorkerEvent::Snapshot(snapshot) => self.model.apply_snapshot(snapshot),
                WorkerEvent::Error { code, message } => self.model.report_error(code, message),
            }
        }
    }

    fn nav_button(
        &self,
        page: DesktopPage,
        label: &'static str,
        index: isize,
        cx: &Context<Self>,
    ) -> Stateful<Div> {
        let selected = self.model.page() == page;
        button(
            ("nav", usize::try_from(index).unwrap_or_default()),
            label,
            index,
        )
        .when(selected, |item| {
            item.bg(rgb(ACCENT)).text_color(rgb(BACKGROUND))
        })
        .on_click(cx.listener(move |this, _, _, cx| this.navigate(page, cx)))
    }

    fn render_sidebar(
        &self,
        cx: &Context<Self>,
    ) -> Div {
        div()
            .w(px(224.0))
            .h_full()
            .flex_none()
            .flex()
            .flex_col()
            .justify_between()
            .p_5()
            .bg(rgb(PANEL))
            .border_r_1()
            .border_color(rgb(BORDER))
            .child(
                div()
                    .flex()
                    .flex_col()
                    .gap_2()
                    .child(
                        div()
                            .text_2xl()
                            .font_weight(FontWeight::BOLD)
                            .mb_6()
                            .child("koe / local"),
                    )
                    .child(self.nav_button(DesktopPage::Setup, "Setup", 1, cx))
                    .child(self.nav_button(DesktopPage::Recorder, "Recorder", 2, cx))
                    .child(self.nav_button(DesktopPage::Models, "Models", 3, cx))
                    .child(self.nav_button(DesktopPage::Sessions, "Sessions", 4, cx))
                    .child(self.nav_button(DesktopPage::Settings, "Privacy", 5, cx)),
            )
            .child(
                div()
                    .text_sm()
                    .text_color(rgb(MUTED))
                    .child("LOCAL INFERENCE")
                    .child("Network denied while recording"),
            )
    }

    fn render_header(&self) -> Div {
        let title = match self.model.page() {
            DesktopPage::Setup => "Prepare your workspace",
            DesktopPage::Recorder => "Recorder",
            DesktopPage::Models => "Model manager",
            DesktopPage::Sessions => "Session library",
            DesktopPage::Settings => "Privacy & diagnostics",
        };
        div()
            .flex()
            .items_center()
            .justify_between()
            .mb_6()
            .child(div().text_2xl().font_weight(FontWeight::BOLD).child(title))
            .when_some(self.model.recording_indicator(), |header, indicator| {
                header.child(
                    div()
                        .px_3()
                        .py_1()
                        .rounded_full()
                        .bg(rgb(DANGER))
                        .text_color(rgb(BACKGROUND))
                        .font_weight(FontWeight::BOLD)
                        .child(indicator),
                )
            })
    }

    fn render_setup(
        &self,
        cx: &Context<Self>,
    ) -> Div {
        let source_cards = self
            .model
            .sources()
            .iter()
            .enumerate()
            .map(|(index, source)| {
                let name = match source.kind {
                    SourceKind::Microphone => "Microphone",
                    SourceKind::System => "System audio",
                };
                card()
                    .id(("source", index))
                    .child(section_label(name))
                    .child(format!("{:?} / {:?}", source.capability, source.permission))
                    .child(
                        div()
                            .text_sm()
                            .text_color(rgb(MUTED))
                            .child(source.guidance()),
                    )
                    .child(format!("Backend: {}", source.backend))
            });
        let device_count = self
            .devices
            .iter()
            .filter(|device| device.kind == SourceKind::Microphone)
            .count();
        div()
            .flex()
            .flex_col()
            .gap_4()
            .child(
                div()
                    .text_color(rgb(MUTED))
                    .child("Permissions are separate from recording consent. No prompt is opened by this screen."),
            )
            .child(div().flex().gap_4().children(source_cards))
            .child(
                card()
                    .child(section_label("Selection"))
                    .child(format!("{device_count} microphone device(s) detected"))
                    .child(format!(
                        "Model: {}",
                        self.model.selected_model().unwrap_or("audio only")
                    ))
                    .child(format!("Storage: app data root ({})", short_path(&self.data_root)))
                    .child(retention_label(self.model.settings().retention_days)),
            )
            .child(
                button("continue", "Continue to recorder", 10)
                    .on_click(cx.listener(|this, _, _, cx| {
                        this.navigate(DesktopPage::Recorder, cx);
                    })),
            )
    }

    fn render_recorder(
        &self,
        cx: &Context<Self>,
    ) -> Div {
        let can_start = self.model.can_start();
        let active = self.model.recording_indicator().is_some();
        div()
            .flex()
            .flex_col()
            .gap_5()
            .child(
                card()
                    .h(px(220.0))
                    .items_center()
                    .justify_center()
                    .child(div().text_2xl().font_weight(FontWeight::BOLD).child(
                        if self.model.recording_indicator().is_some() {
                            "00:00  RECORDING"
                        } else {
                            "00:00  READY"
                        },
                    ))
                    .child("Live transcript appears here after an installed model starts."),
            )
            .child(
                card()
                    .child(section_label("Consent review"))
                    .child(format!(
                        "Microphone: {}",
                        self.model.selected_microphone().unwrap_or("not selected")
                    ))
                    .child(format!(
                        "System audio: {}",
                        self.model.selected_system_audio().unwrap_or("not captured")
                    ))
                    .child(format!(
                        "ASR: {} (local only)",
                        self.model.selected_model().unwrap_or("disabled")
                    ))
                    .child(retention_label(self.model.settings().retention_days))
                    .child("Sharing: none"),
            )
            .child(
                button(
                    "record",
                    if active {
                        "Stop & finalize recording"
                    } else {
                        "Confirm & start recording"
                    },
                    10,
                )
                .when(!can_start && !active, |item| item.opacity(0.45))
                .on_click(cx.listener(move |this, _, _, cx| {
                    if active {
                        if this.capture.stop().is_err() {
                            this.model.report_error(
                                "KOE-SESSION-COORDINATOR-STOPPED",
                                "Capture worker stopped",
                            );
                        }
                    } else if can_start {
                        this.model.confirm_recording();
                        let consent = this.model.take_recording_consent();
                        let microphone = this.model.selected_microphone().map(str::to_owned);
                        if let Some(microphone) = microphone
                            && this
                                .capture
                                .start(this.data_root.clone(), microphone, consent)
                                .is_err()
                        {
                            this.model.report_error(
                                "KOE-SESSION-COORDINATOR-STOPPED",
                                "Capture worker stopped",
                            );
                        }
                    }
                    cx.notify();
                })),
            )
            .child(
                div()
                    .text_sm()
                    .text_color(rgb(MUTED))
                    .child(self.model.status_message().to_owned()),
            )
    }

    fn render_models(&self) -> Div {
        let rows = self.models.iter().enumerate().map(|(index, model)| {
            card()
                .id(("model", index))
                .child(section_label(&model.alias))
                .child(format!("{} / {}", model.version, model.provider))
                .child(format!("License: {}", model.license))
                .child(format!("Artifact size: {} MiB", model.size / 1_048_576))
                .child(
                    div()
                        .text_sm()
                        .text_color(rgb(MUTED))
                        .child(model.id.clone()),
                )
        });
        div()
            .flex()
            .flex_col()
            .gap_4()
            .child("Downloads require an explicit online action and license review. Recording never downloads a model.")
            .children(rows)
            .when(self.models.is_empty(), |content| {
                content.child(card().child("No locally installed models."))
            })
    }

    fn render_sessions(&self) -> Div {
        let rows = self.sessions.iter().enumerate().map(|(index, session)| {
            card()
                .id(("session", index))
                .child(section_label(&format!("Session {}", short_id(&session.id))))
                .child(format!(
                    "{} / {} sec / {} audio file(s)",
                    session.state,
                    session.duration_ms / 1_000,
                    session.files
                ))
                .child(if session.has_transcript {
                    "Transcript ready"
                } else {
                    "No transcript"
                })
                .child("Export and delete require an explicit destination/confirmation.")
        });
        div()
            .flex()
            .flex_col()
            .gap_4()
            .children(rows)
            .when(self.sessions.is_empty(), |content| {
                content.child(card().child("No sessions yet."))
            })
    }

    fn render_settings(
        &self,
        cx: &Context<Self>,
    ) -> Div {
        let settings = self.model.settings();
        div()
            .flex()
            .flex_col()
            .gap_4()
            .child(
                card()
                    .child(section_label("Offline policy"))
                    .child("Inference and recording are local-only. Network is denied during sessions.")
                    .child(toggle_button("offline", settings.offline_only, 10).on_click(
                        cx.listener(|this, _, _, cx| {
                            let mut settings = this.model.settings();
                            settings.offline_only = true;
                            this.save_settings(settings);
                            cx.notify();
                        }),
                    )),
            )
            .child(
                card()
                    .child(section_label("Retention"))
                    .child(retention_label(settings.retention_days))
                    .child("Automatic deletion never removes active sessions. Filesystem deletion may not physically erase SSD snapshots or backups.")
                    .child(button("retention", "Cycle: forever / 30 / 7 days", 11).on_click(
                        cx.listener(|this, _, _, cx| {
                            let mut settings = this.model.settings();
                            settings.retention_days = match settings.retention_days {
                                None => Some(30),
                                Some(30) => Some(7),
                                Some(_) => None,
                            };
                            this.save_settings(settings);
                            cx.notify();
                        }),
                    )),
            )
            .child(
                card()
                    .child(section_label("Diagnostics"))
                    .child("Diagnostics exclude audio, transcript text, secrets and complete paths.")
                    .child(toggle_button("diagnostics", settings.diagnostics_enabled, 12).on_click(
                        cx.listener(|this, _, _, cx| {
                            let mut settings = this.model.settings();
                            settings.diagnostics_enabled = !settings.diagnostics_enabled;
                            this.save_settings(settings);
                            cx.notify();
                        }),
                    )),
            )
    }

    fn save_settings(
        &mut self,
        settings: DesktopSettings,
    ) {
        let stored = StoredSettings {
            schema_version: 1,
            retention_days: settings.retention_days,
            diagnostics_enabled: settings.diagnostics_enabled,
            offline_only: true,
        };
        if save_settings(&self.data_root, &stored).is_ok() {
            self.model.set_settings(settings);
        } else {
            self.model
                .report_error("KOE-CONFIG-IO-FAILED", "Could not save settings");
        }
    }
}

impl Render for KoeDesktop {
    #[allow(clippy::needless_pass_by_ref_mut)]
    fn render(
        &mut self,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) -> impl IntoElement {
        window.set_window_title(self.model.recording_indicator().map_or(
            "koe - offline recorder",
            |indicator| {
                if indicator == "FINALIZING" {
                    "koe - FINALIZING"
                } else {
                    "koe - RECORDING"
                }
            },
        ));
        let content = match self.model.page() {
            DesktopPage::Setup => self.render_setup(cx),
            DesktopPage::Recorder => self.render_recorder(cx),
            DesktopPage::Models => self.render_models(),
            DesktopPage::Sessions => self.render_sessions(),
            DesktopPage::Settings => self.render_settings(cx),
        };
        div()
            .id("koe-desktop")
            .track_focus(&self.focus)
            .on_action(cx.listener(Self::on_tab))
            .on_action(cx.listener(Self::on_tab_prev))
            .size_full()
            .flex()
            .bg(rgb(BACKGROUND))
            .text_color(rgb(TEXT))
            .font_family("Menlo")
            .child(self.render_sidebar(cx))
            .child(
                div()
                    .id("content")
                    .flex_1()
                    .h_full()
                    .overflow_y_scroll()
                    .p_8()
                    .child(self.render_header())
                    .child(content),
            )
    }
}

fn button(
    id: impl Into<ElementId>,
    label: impl Into<String>,
    index: isize,
) -> Stateful<Div> {
    let label = label.into();
    div()
        .id(id)
        .tab_index(index)
        .px_3()
        .py_2()
        .rounded_md()
        .border_1()
        .border_color(rgb(BORDER))
        .cursor_pointer()
        .hover(|item| item.bg(rgb(BORDER)))
        .focus(|item| item.border_color(rgb(ACCENT)))
        .child(label)
}

fn toggle_button(
    id: &'static str,
    enabled: bool,
    index: isize,
) -> Stateful<Div> {
    button(id, if enabled { "Enabled" } else { "Disabled" }, index).when(enabled, |item| {
        item.bg(rgb(ACCENT)).text_color(rgb(BACKGROUND))
    })
}

fn card() -> Div {
    div()
        .flex()
        .flex_col()
        .gap_2()
        .p_5()
        .rounded_lg()
        .border_1()
        .border_color(rgb(BORDER))
        .bg(rgb(PANEL))
}

fn section_label(label: &str) -> Div {
    div().font_weight(FontWeight::BOLD).child(label.to_owned())
}

fn capture_worker(
    commands: &mpsc::Receiver<WorkerCommand>,
    events: &mpsc::Sender<WorkerEvent>,
) {
    while let Ok(command) = commands.recv() {
        match command {
            WorkerCommand::Start {
                data_root,
                device_id,
                consent,
            } => {
                if run_capture(commands, events, &data_root, &device_id, consent) {
                    break;
                }
            },
            WorkerCommand::Stop => {},
            WorkerCommand::Shutdown => break,
        }
    }
}

#[allow(clippy::too_many_lines)]
fn run_capture(
    commands: &mpsc::Receiver<WorkerCommand>,
    events: &mpsc::Sender<WorkerEvent>,
    data_root: &Path,
    device_id: &str,
    consent: RecordingConsent,
) -> bool {
    let backend = CpalBackend::default();
    let request = OpenSource {
        device_id: device_id.to_owned(),
        kind: SourceKind::Microphone,
        sample_rate: 48_000,
        channels: 1,
    };
    let Ok(mut stream) = backend.open(&request) else {
        send_worker_error(events, "KOE-AUDIO-DEVICE-LOST", "Could not open microphone");
        return false;
    };
    let mut config =
        RecordingConfig::microphone(data_root, stream.sample_rate(), stream.channels());
    device_id.clone_into(&mut config.source_device_id);
    "pending-stream-start".clone_into(&mut config.permission_result);
    stream
        .native_sample_format()
        .manifest_label()
        .clone_into(&mut config.native_sample_format);
    config.backend = backend
        .enumerate(SourceKind::Microphone)
        .ok()
        .and_then(|devices| devices.into_iter().find(|device| device.id == device_id))
        .map_or_else(|| "unknown".to_owned(), |device| device.backend);
    let queue_capacity = config.queue_capacity;
    let Ok((producer, consumer)) = frame_ring(queue_capacity, 16_384) else {
        send_worker_error(events, "KOE-AUDIO-OVERFLOW", "Could not create audio queue");
        return false;
    };
    let (coordinator, task) = RecorderCoordinator::spawn(config);
    let Ok(starting) = coordinator.start(consent) else {
        send_worker_error(
            events,
            "KOE-POLICY-CONSENT-REQUIRED",
            "Fresh recording consent is required",
        );
        let _shutdown = task.shutdown(&coordinator);
        return false;
    };
    let _starting = events.send(WorkerEvent::Snapshot(starting));
    if let Err(error) = stream.start(Box::new(producer)) {
        let _failed = coordinator.fail(error.code());
        send_worker_error(
            events,
            error.code(),
            "Microphone permission or stream start failed",
        );
        let _shutdown = task.shutdown(&coordinator);
        return false;
    }
    let _permission = coordinator.record_permission_result(TrackKind::Microphone, "granted");
    if coordinator.mark_recording().is_err() {
        let _stopped = stream.stop();
        send_worker_error(events, "KOE-SESSION-CONFLICT", "Could not start session");
        let _shutdown = task.shutdown(&coordinator);
        return false;
    }
    if let Ok(snapshot) = coordinator.snapshot() {
        let _recording = events.send(WorkerEvent::Snapshot(snapshot));
    }

    let mut samples = vec![0_i16; 16_384];
    let mut shutdown = false;
    let mut cancel = false;
    loop {
        match commands.try_recv() {
            Ok(WorkerCommand::Stop) => break,
            Ok(WorkerCommand::Shutdown) | Err(mpsc::TryRecvError::Disconnected) => {
                shutdown = true;
                cancel = true;
                break;
            },
            Ok(WorkerCommand::Start { .. }) => send_worker_error(
                events,
                "KOE-SESSION-CONFLICT",
                "Another recording session is active",
            ),
            Err(mpsc::TryRecvError::Empty) => {},
        }
        let dropped = consumer.take_dropped_frames();
        if dropped != 0 {
            let _overflow = coordinator.record_overflow(TrackKind::Microphone, dropped);
        }
        if let Some(failure) = consumer.take_runtime_failure() {
            let error = failure.audio_error();
            let _failed = coordinator.fail(error.code());
            send_worker_error(
                events,
                error.code(),
                "Microphone permission or device was lost",
            );
            cancel = true;
        } else if consumer.take_device_lost() {
            let _failed = coordinator.fail("KOE-AUDIO-DEVICE-LOST");
            send_worker_error(
                events,
                "KOE-AUDIO-DEVICE-LOST",
                "Microphone device was lost",
            );
            cancel = true;
        }
        if cancel {
            break;
        }
        loop {
            match consumer.try_pop(&mut samples) {
                Ok(Some(metadata)) => {
                    if let Some(failure) = metadata.runtime_failure {
                        let error = failure.audio_error();
                        let _failed = coordinator.fail(error.code());
                        send_worker_error(events, error.code(), "Microphone stream failed");
                        cancel = true;
                        break;
                    }
                    let count = usize::try_from(metadata.sample_count)
                        .unwrap_or(0)
                        .min(samples.len());
                    if count != 0 && coordinator.append(samples[..count].to_vec()).is_err() {
                        send_worker_error(
                            events,
                            "KOE-STORE-FINALIZE-FAILED",
                            "Recording writer failed",
                        );
                        cancel = true;
                        break;
                    }
                },
                Ok(None) => break,
                Err(_) => {
                    send_worker_error(events, "KOE-AUDIO-OVERFLOW", "Audio queue failed");
                    cancel = true;
                    break;
                },
            }
        }
        if cancel {
            break;
        }
        thread::sleep(Duration::from_millis(5));
    }

    let _stopped = stream.stop();
    let terminal = if cancel {
        coordinator.cancel()
    } else {
        coordinator.stop()
    };
    match terminal {
        Ok(snapshot) => {
            let _terminal = events.send(WorkerEvent::Snapshot(snapshot));
        },
        Err(error) => send_worker_error(events, error.code(), "Could not finalize recording"),
    }
    let _shutdown = task.shutdown(&coordinator);
    shutdown
}

fn send_worker_error(
    events: &mpsc::Sender<WorkerEvent>,
    code: &'static str,
    message: &'static str,
) {
    let _error = events.send(WorkerEvent::Error { code, message });
}

fn load_audio() -> (Vec<SourceStatus>, Vec<AudioDevice>) {
    let backend = CpalBackend::default();
    let capabilities = backend.capabilities().unwrap_or_default();
    let permissions = backend
        .permissions()
        .unwrap_or_else(|_| capabilities.clone());
    let sources = capabilities
        .into_iter()
        .map(|capability| source_status(capability, &permissions))
        .collect();
    let mut devices = backend
        .enumerate(SourceKind::Microphone)
        .unwrap_or_default();
    devices.extend(backend.enumerate(SourceKind::System).unwrap_or_default());
    (sources, devices)
}

fn source_status(
    capability: AudioCapability,
    permissions: &[AudioCapability],
) -> SourceStatus {
    let permission = permissions
        .iter()
        .find(|status| status.source == capability.source)
        .map_or(capability.permission, |status| status.permission);
    SourceStatus {
        kind: capability.source,
        capability: capability.state,
        permission,
        backend: capability.backend,
    }
}

fn load_models(data_root: &Path) -> Vec<ModelRow> {
    let Ok(manager) = KoeModelManager::new(
        data_root,
        DigestAllowlist::empty(),
        Box::new(FoundryLocalAdapter::new()),
        NetworkPolicy::Denied,
    ) else {
        return Vec::new();
    };
    manager.installed_models().map_or_else(
        |_| Vec::new(),
        |models| {
            models
                .into_iter()
                .map(|model| ModelRow {
                    id: model.id.to_string(),
                    alias: model.manifest.alias.0,
                    version: model.manifest.version.0,
                    provider: model.manifest.provider,
                    license: model.manifest.license_id,
                    size: model.manifest.files.iter().map(|file| file.size).sum(),
                })
                .collect()
        },
    )
}

fn load_sessions(data_root: &Path) -> Vec<SessionRow> {
    let Ok(entries) = fs::read_dir(data_root.join("sessions")) else {
        return Vec::new();
    };
    let mut rows = Vec::new();
    for entry in entries.flatten() {
        if entry
            .file_type()
            .is_ok_and(|kind| kind.is_dir() && !kind.is_symlink())
            && let Ok(bytes) = fs::read(entry.path().join("session.json"))
            && let Ok(manifest) = serde_json::from_slice::<SessionManifest>(&bytes)
        {
            let duration_ms = manifest.ended_unix_ms.map_or(0, |end| {
                u64::try_from(end.saturating_sub(manifest.started_unix_ms)).unwrap_or(u64::MAX)
            });
            rows.push(SessionRow {
                id: manifest.session_id.to_string(),
                state: format!("{:?}", manifest.state).to_lowercase(),
                duration_ms,
                files: manifest.audio_files.len(),
                has_transcript: entry.path().join("transcript/final.json").is_file(),
            });
        }
    }
    rows
}

fn data_root() -> PathBuf {
    if let Some(root) = std::env::var_os("KOE_DATA_ROOT") {
        return PathBuf::from(root);
    }
    let base = std::env::var_os(if cfg!(windows) {
        "LOCALAPPDATA"
    } else {
        "HOME"
    })
    .map_or_else(|| PathBuf::from("."), PathBuf::from);
    if cfg!(target_os = "macos") {
        base.join("Library/Application Support/dev.mokmok.koe")
    } else if cfg!(windows) {
        base.join("koe")
    } else {
        base.join(".local/share/koe")
    }
}

fn load_settings(data_root: &Path) -> StoredSettings {
    fs::read(data_root.join("desktop-settings.json"))
        .ok()
        .and_then(|bytes| serde_json::from_slice(&bytes).ok())
        .filter(|settings: &StoredSettings| settings.schema_version == 1)
        .unwrap_or_default()
}

fn save_settings(
    data_root: &Path,
    settings: &StoredSettings,
) -> Result<(), std::io::Error> {
    let temporary = data_root.join(".desktop-settings.json.tmp");
    let bytes = serde_json::to_vec_pretty(settings).map_err(std::io::Error::other)?;
    fs::write(&temporary, bytes)?;
    fs::rename(temporary, data_root.join("desktop-settings.json"))
}

fn retention_label(days: Option<u32>) -> String {
    days.map_or_else(
        || "Retention: forever, until explicitly deleted".to_owned(),
        |days| format!("Retention: {days} days"),
    )
}

fn short_id(id: &str) -> &str {
    id.get(..8).unwrap_or(id)
}

fn short_path(path: &Path) -> String {
    path.file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("koe")
        .to_owned()
}

fn main() {
    Application::new().run(|cx: &mut App| {
        cx.bind_keys([
            KeyBinding::new("tab", Tab, None),
            KeyBinding::new("shift-tab", TabPrev, None),
        ]);
        let bounds = Bounds::centered(None, size(px(1_080.0), px(720.0)), cx);
        let result = cx.open_window(
            WindowOptions {
                window_bounds: Some(WindowBounds::Windowed(bounds)),
                window_min_size: Some(size(px(760.0), px(540.0))),
                titlebar: Some(gpui::TitlebarOptions {
                    title: Some("koe - offline recorder".into()),
                    ..Default::default()
                }),
                app_id: Some("dev.mokmok.koe".to_owned()),
                ..Default::default()
            },
            |window, cx| cx.new(|cx| KoeDesktop::new(window, cx)),
        );
        if result.is_ok() {
            cx.activate(true);
        }
    });
}

#[cfg(test)]
mod tests {
    use tempfile::TempDir;

    use super::{StoredSettings, load_sessions, load_settings, save_settings};

    #[test]
    fn privacy_defaults_are_offline_and_opt_in() {
        let root = TempDir::new().expect("temp");
        let settings = load_settings(root.path());
        assert!(settings.offline_only);
        assert!(!settings.diagnostics_enabled);
        assert_eq!(settings.retention_days, None);
    }

    #[test]
    fn settings_are_persisted_atomically() {
        let root = TempDir::new().expect("temp");
        let settings = StoredSettings {
            retention_days: Some(7),
            diagnostics_enabled: true,
            ..StoredSettings::default()
        };
        save_settings(root.path(), &settings).expect("save");
        let loaded = load_settings(root.path());
        assert_eq!(loaded.retention_days, Some(7));
        assert!(loaded.diagnostics_enabled);
    }

    #[test]
    fn fresh_session_library_is_empty() {
        let root = TempDir::new().expect("temp");
        assert!(load_sessions(root.path()).is_empty());
    }
}
