//! Stable domain types shared by all koe frontends and adapters.

use std::fmt;

use serde::{Deserialize, Serialize};
use thiserror::Error;
use uuid::Uuid;

/// Identifier generated by koe, never from user-controlled path text.
#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, PartialEq, Serialize)]
#[serde(transparent)]
pub struct SessionId(Uuid);

impl SessionId {
    /// Creates a collision-resistant session identifier.
    #[must_use]
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }

    /// Parses the canonical UUID representation.
    ///
    /// # Errors
    ///
    /// Returns [`CoreError::InvalidSessionId`] when `value` is not a UUID.
    pub fn parse(value: &str) -> Result<Self, CoreError> {
        Uuid::parse_str(value)
            .map(Self)
            .map_err(|_| CoreError::InvalidSessionId)
    }
}

impl Default for SessionId {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for SessionId {
    fn fmt(
        &self,
        formatter: &mut fmt::Formatter<'_>,
    ) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

/// Correlates a long-running operation across frontends.
#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, PartialEq, Serialize)]
#[serde(transparent)]
pub struct OperationId(Uuid);

impl OperationId {
    /// Creates a new operation identifier.
    #[must_use]
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }
}

impl Default for OperationId {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for OperationId {
    fn fmt(
        &self,
        formatter: &mut fmt::Formatter<'_>,
    ) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

/// Recording lifecycle defined by `spec/03-core-architecture.md`.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum SessionState {
    Idle,
    Preparing,
    PermissionRequired,
    Starting,
    Recording,
    Degraded,
    Stopping,
    Finalizing,
    Completed,
    Cancelling,
    Cancelled,
    Failed,
    RecoveredPartial,
}

impl SessionState {
    /// Whether no more normal state transitions are allowed.
    #[must_use]
    pub const fn is_terminal(self) -> bool {
        matches!(
            self,
            Self::Completed | Self::Cancelled | Self::Failed | Self::RecoveredPartial
        )
    }

    const fn allows(
        self,
        next: Self,
    ) -> bool {
        use SessionState::{
            Cancelled, Cancelling, Completed, Degraded, Failed, Finalizing, Idle,
            PermissionRequired, Preparing, Recording, Starting, Stopping,
        };

        matches!(
            (self, next),
            (Idle, Preparing)
                | (
                    Preparing,
                    PermissionRequired | Starting | Cancelling | Failed
                )
                | (PermissionRequired, Starting | Failed)
                | (Starting, Recording | Degraded | Cancelling | Failed)
                | (Recording, Degraded | Stopping | Cancelling | Failed)
                | (Degraded, Recording | Stopping | Cancelling | Failed)
                | (Stopping | Cancelling, Finalizing | Failed)
                | (Finalizing, Completed | Cancelled | Failed)
        )
    }
}

/// Checked session state machine. Repeating a terminal transition is idempotent.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct SessionLifecycle {
    state: SessionState,
}

impl SessionLifecycle {
    /// Starts in the idle state.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            state: SessionState::Idle,
        }
    }

    /// Returns the latest durable state.
    #[must_use]
    pub const fn state(&self) -> SessionState {
        self.state
    }

    /// Applies a legal transition.
    ///
    /// # Errors
    ///
    /// Returns [`CoreError::InvalidTransition`] for a transition not present in the
    /// lifecycle specification.
    pub fn transition(
        &mut self,
        next: SessionState,
    ) -> Result<(), CoreError> {
        if self.state == next && next.is_terminal() {
            return Ok(());
        }
        if !self.state.allows(next) {
            return Err(CoreError::InvalidTransition {
                from: self.state,
                to: next,
            });
        }
        self.state = next;
        Ok(())
    }
}

impl Default for SessionLifecycle {
    fn default() -> Self {
        Self::new()
    }
}

/// Audio source category exposed without leaking an OS backend type.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum SourceKind {
    Microphone,
    System,
}

/// Stable machine-readable capability state.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum CapabilityState {
    Supported,
    Unsupported,
    PermissionRequired,
}

/// Runtime availability independent from the current permission decision.
#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum Availability {
    Available,
    OsTooOld,
    ApiUnavailable,
    BackendUnavailable,
    #[default]
    Unsupported,
}

/// Permission state without conflating hardware/backend availability.
#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum PermissionState {
    Granted,
    NotDetermined,
    Denied,
    Restricted,
    Revoked,
    /// The platform has no side-effect-free status API.
    Unobservable,
    #[default]
    NotApplicable,
}

/// Side effects a capability probe is allowed to perform.
#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum ProbeEffect {
    #[default]
    None,
    MayPrompt,
    OpensCapture,
}

/// Network access frozen at session start.
#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum NetworkPolicy {
    #[default]
    Denied,
    ModelInstallOnly,
    Allowed,
}

/// Stable public failures. Messages intentionally contain no paths or content.
#[derive(Clone, Copy, Debug, Error, Eq, PartialEq)]
pub enum CoreError {
    #[error("invalid session identifier")]
    InvalidSessionId,
    #[error("invalid session transition from {from:?} to {to:?}")]
    InvalidTransition {
        from: SessionState,
        to: SessionState,
    },
    #[error("another recording session is active")]
    SessionConflict,
    #[error("recording consent is required")]
    ConsentRequired,
}

impl CoreError {
    /// Stable code suitable for CLI, UI and MCP.
    #[must_use]
    pub const fn code(self) -> &'static str {
        match self {
            Self::InvalidSessionId => "KOE-STORE-PATH-REJECTED",
            Self::InvalidTransition { .. } | Self::SessionConflict => "KOE-SESSION-CONFLICT",
            Self::ConsentRequired => "KOE-POLICY-CONSENT-REQUIRED",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{SessionLifecycle, SessionState};

    #[test]
    fn happy_path_reaches_completed() {
        let mut lifecycle = SessionLifecycle::new();
        for state in [
            SessionState::Preparing,
            SessionState::Starting,
            SessionState::Recording,
            SessionState::Stopping,
            SessionState::Finalizing,
            SessionState::Completed,
        ] {
            assert!(lifecycle.transition(state).is_ok());
        }
        assert_eq!(lifecycle.state(), SessionState::Completed);
    }

    #[test]
    fn terminal_transition_is_idempotent() {
        let mut lifecycle = SessionLifecycle {
            state: SessionState::Completed,
        };
        assert!(lifecycle.transition(SessionState::Completed).is_ok());
    }

    #[test]
    fn invalid_transition_preserves_state() {
        let mut lifecycle = SessionLifecycle::new();
        assert!(lifecycle.transition(SessionState::Recording).is_err());
        assert_eq!(lifecycle.state(), SessionState::Idle);
    }

    #[test]
    fn degraded_session_can_recover_or_stop() {
        let mut lifecycle = SessionLifecycle {
            state: SessionState::Recording,
        };
        assert!(lifecycle.transition(SessionState::Degraded).is_ok());
        assert!(lifecycle.transition(SessionState::Recording).is_ok());
    }
}
