name: nix
on:
  pull_request:
  push:
    branches:
      - "main"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-nix
  cancel-in-progress: true
permissions:
  contents: read
  actions: write
  id-token: write
jobs:
  check:
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
          - runs-on: macos-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-nix
      - run: nix flake check
        shell: bash
